### ISSUE TITLE
Are there any documentation beside the test case?

### ISSUE THREAD

**Issue by MarisaKirisame** [Kalimehtar/gls#1]
The test case only seems to cover the most basic usage.

**Comment by Kalimehtar** [comment]
Most patterns are explained in https://github.com/gregsgit/glos/blob/master/ref-dyn-patterns.pdf

If you are interested in GLS, I'll write the documentation. In the current state it is more proof of concept (that one can make generics without classes), than production library.

**Comment by MarisaKirisame** [comment]
I'd say don't worry, I am looking for a solution for multi dispatch for a project, but since this is a unstable library, documenting it doesn't seems to worth the trouble... I can read the source

**Comment by Kalimehtar** [comment]
This solution is good, because it is most flexible. No need of classes. No [circle-ellipse problem](https://en.wikipedia.org/wiki/Circle-ellipse_problem) , because type of item depends on its value. Methods may be added in different modules. Allows before- after- and around- methods like [CLOS](https://en.wikipedia.org/wiki/Common_Lisp_Object_System)

This solution is slow. O(number of methods) in common case. If you need fast multi dispatch, better look at [swindle](https://github.com/racket/swindle), or even better [fast generic](http://wiki.call-cc.org/eggref/4/fast-generic).

**Comment by MarisaKirisame** [comment]
I cannot open the lowest two link, but speed is certainly not an issue here. Even if it's time is second, it's still fast enough for a stratego game...

**Comment by Kalimehtar** [comment]
I fixed previous message: now links are working. If you have any concrete questions about syntax of gls, please ask, I'll answer here.

**Comment by MarisaKirisame** [comment]
Thx
